import 'dart:math';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../config/design_system.dart';
import '../constants/app_constants.dart';
import '../models/inventory_item_model.dart';
import '../providers/inventory_provider.dart';
import '../services/secure_storage_service.dart';
import '../widgets/glass_card.dart';
import '../widgets/inventory_stat_card.dart';
import '../widgets/stock_adjustment_modal.dart';
import '../widgets/inventory_history_modal.dart';
import '../widgets/batch_registration_modal.dart';
import '../widgets/app_bar_glass.dart';

class FarmsInventoryPage extends StatefulWidget {
  const FarmsInventoryPage({super.key});

  @override
  State<FarmsInventoryPage> createState() => _FarmsInventoryPageState();
}

class _FarmsInventoryPageState extends State<FarmsInventoryPage>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  final _secureStorage = SecureStorageService();
  final _formKey = GlobalKey<FormState>();

  String? _authToken;
  bool _showForm = false;
  int? _editingId;
  String? _selectedCategory;
  String _searchQuery = '';

  // Batch registration state
  List<String> _batchQueue = [];
  int _currentQueueIndex = -1;
  String _globalBatchName = '';
  bool _isBatchAutoGenerated = true;

  // Form state
  final Map<String, dynamic> _formData = {
    'item_name': '',
    'category': 'Source Resource',
    'inventory_type': 'Consumable',
    'source_resource': '',
    'quantity_purchased': '',
    'unit': 'units',
    'unit_price': '',
    'purchase_date': '',
  };

  // Category configuration
  final Map<String, CategoryConfig> _categoryConfig = {
    'Source Resource': CategoryConfig(
      icon: Icons.factory,
      color: const Color(0xFF64748B),
      bgColor: const Color(0x1A64748B),
    ),
    'Non-Scarce Items': CategoryConfig(
      icon: Icons.archive,
      color: const Color(0xFFF59E0B),
      bgColor: const Color(0x1AF59E0B),
    ),
    'Fertilizer': CategoryConfig(
      icon: Icons.eco,
      color: AppConstants.forestGreen,
      bgColor: const Color(0x1A74981E),
    ),
    'Pesticides': CategoryConfig(
      icon: Icons.bug_report,
      color: Colors.red,
      bgColor: const Color(0x1AEF4444),
    ),
    'Fungicides': CategoryConfig(
      icon: Icons.local_florist,
      color: Colors.purple,
      bgColor: const Color(0x1A9333EA),
    ),
    'Seeds': CategoryConfig(
      icon: Icons.grass,
      color: Colors.green,
      bgColor: const Color(0x1A10B981),
    ),
    'Tools': CategoryConfig(
      icon: Icons.handyman,
      color: Colors.blue,
      bgColor: const Color(0x1A3B82F6),
    ),
    'Equipment': CategoryConfig(
      icon: Icons.construction,
      color: Colors.orange,
      bgColor: const Color(0x1AF97316),
    ),
    'Irrigation': CategoryConfig(
      icon: Icons.water_drop,
      color: Colors.cyan,
      bgColor: const Color(0x1A06B6D4),
    ),
  };

  final List<String> _inventoryTypes = ['Consumable', 'Asset', 'Service'];
  final List<String> _units = [
    'kg',
    'liter',
    'mililiter',
    'units',
    'pieces',
    'bottles',
    'packets',
  ];

  @override
  void initState() {
    super.initState();
    _loadToken();
    _formData['purchase_date'] = _getTodayDate();
  }

  String _getTodayDate() {
    final now = DateTime.now();
    return '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
  }

  Future<void> _loadToken() async {
    _authToken = await _secureStorage.getAuthToken();
    if (_authToken != null && mounted) {
      final inventoryProvider =
          Provider.of<InventoryProvider>(context, listen: false);
      await inventoryProvider.fetchInventory(_authToken!);
    }
  }

  Future<void> _handleRefresh() async {
    if (_authToken != null) {
      final inventoryProvider =
          Provider.of<InventoryProvider>(context, listen: false);
      await inventoryProvider.fetchInventory(_authToken!);
    }
  }

  void _handleAddNew() {
    _isBatchAutoGenerated = true;
    if (_selectedCategory != null) {
      _showModeSelectionDialog();
    } else {
      _openFormWithCategory(_categoryConfig.keys.first);
    }
  }

  void _showModeSelectionDialog() {
    showDialog(
      context: context,
      builder: (context) => BatchRegistrationModal(
        selectedCategory: _selectedCategory!,
        onSingleMode: () {
          _openFormWithCategory(_selectedCategory!);
        },
        onBatchMode: (categories, batchName) {
          _startBatchRegistration(categories, batchName);
        },
      ),
    );
  }

  void _openFormWithCategory(String category, [String batchName = '']) {
    setState(() {
      _formData['item_name'] = '';
      _formData['category'] = category;
      _formData['inventory_type'] = 'Consumable';
      _formData['source_resource'] = batchName;
      _formData['quantity_purchased'] = '';
      _formData['unit'] = 'units';
      _formData['unit_price'] = '';
      _formData['purchase_date'] = _getTodayDate();
      _editingId = null;
      _showForm = true;
    });
  }

  void _startBatchRegistration(List<String> categories, String batchName) {
    final queue = [_selectedCategory!, ...categories];
    setState(() {
      _batchQueue = queue;
      _currentQueueIndex = 0;
      _globalBatchName = batchName;
    });
    _openFormWithCategory(queue[0], batchName);
  }

  void _closeForm() {
    setState(() {
      _showForm = false;
      _batchQueue = [];
      _currentQueueIndex = -1;
      _globalBatchName = '';
    });
  }

  void _handleEdit(InventoryItem item) {
    _isBatchAutoGenerated = false;
    setState(() {
      _formData['item_name'] = item.itemName;
      _formData['category'] = item.category;
      _formData['inventory_type'] = item.inventoryType;
      _formData['source_resource'] = item.sourceResource ?? '';
      _formData['quantity_purchased'] = item.quantityPurchased.toString();
      _formData['unit'] = item.unit;
      _formData['unit_price'] = item.unitPrice.toString();
      _formData['purchase_date'] = item.purchaseDate;
      _editingId = item.id;
      _showForm = true;
    });
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please fill all required fields'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    if (_authToken == null) return;

    final inventoryProvider =
        Provider.of<InventoryProvider>(context, listen: false);

    bool success;
    if (_editingId != null) {
      // Update existing item
      success = await inventoryProvider.updateItem(
        token: _authToken!,
        id: _editingId!,
        itemName: _formData['item_name'],
        category: _formData['category'],
        inventoryType: _formData['inventory_type'],
        sourceResource: _formData['source_resource'].isEmpty
            ? null
            : _formData['source_resource'],
        quantityPurchased: int.parse(_formData['quantity_purchased']),
        quantityAvailable: int.parse(_formData['quantity_purchased']),
        unit: _formData['unit'],
        unitPrice: double.parse(_formData['unit_price']),
        purchaseDate: _formData['purchase_date'],
      );
    } else {
      // Create new item
      success = await inventoryProvider.createItem(
        token: _authToken!,
        itemName: _formData['item_name'],
        category: _formData['category'],
        inventoryType: _formData['inventory_type'],
        sourceResource: _formData['source_resource'].isEmpty
            ? null
            : _formData['source_resource'],
        quantityPurchased: int.parse(_formData['quantity_purchased']),
        unit: _formData['unit'],
        unitPrice: double.parse(_formData['unit_price']),
        purchaseDate: _formData['purchase_date'],
      );
    }

    if (mounted) {
      if (success) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(_editingId != null
                ? 'Item updated successfully'
                : 'Item created successfully'),
            backgroundColor: AppConstants.forestGreen,
          ),
        );

        // Handle sequential batch registration
        if (_currentQueueIndex != -1 &&
            _currentQueueIndex < _batchQueue.length - 1) {
          final nextIndex = _currentQueueIndex + 1;
          setState(() {
            _currentQueueIndex = nextIndex;
            _selectedCategory = _batchQueue[nextIndex];
          });
          _openFormWithCategory(_batchQueue[nextIndex], _globalBatchName);
        } else {
          _closeForm();
        }
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(inventoryProvider.error ?? 'Failed to save item'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _handleDelete(int id, String itemName) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(
          'Delete Item',
          style: DesignSystem.heading(fontWeight: FontWeight.w600),
        ),
        content: Text(
          'Are you sure you want to delete "$itemName"?',
          style: DesignSystem.text(),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text('Cancel', style: DesignSystem.text()),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: Text('Delete', style: DesignSystem.text()),
          ),
        ],
      ),
    );

    if (confirmed == true && _authToken != null && mounted) {
      final inventoryProvider =
          Provider.of<InventoryProvider>(context, listen: false);
      final success = await inventoryProvider.deleteItem(
        token: _authToken!,
        id: id,
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(success
                ? 'Item deleted successfully'
                : inventoryProvider.error ?? 'Failed to delete item'),
            backgroundColor: success ? AppConstants.forestGreen : Colors.red,
          ),
        );
      }
    }
  }

  String _generateBatchNumber() {
    if (_editingId != null ||
        !_isBatchAutoGenerated ||
        _formData['category'].isEmpty ||
        _formData['item_name'].isEmpty ||
        _formData['purchase_date'].isEmpty) {
      return _formData['source_resource'];
    }

    final inventoryProvider =
        Provider.of<InventoryProvider>(context, listen: false);
    final existingItems = inventoryProvider.items;

    // Type prefix
    String typePrefix;
    if (_formData['category'] == 'Fertilizer') {
      typePrefix = 'FER';
    } else if (_formData['category'] == 'Pesticides') {
      typePrefix = 'PES';
    } else if (_formData['category'] == 'Fungicides') {
      typePrefix = 'FUN';
    } else {
      typePrefix = _formData['category']
          .toString()
          .substring(0, min(3, _formData['category'].toString().length))
          .toUpperCase();
    }

    // Name prefix (first 4 chars)
    final itemName = _formData['item_name'].toString().replaceAll(' ', '');
    final namePrefix =
        itemName.substring(0, min(4, itemName.length)).toUpperCase();

    // Date prefix (DDMM)
    final dateParts = _formData['purchase_date'].toString().split('-');
    if (dateParts.length != 3) return _formData['source_resource'];
    final datePrefix = '${dateParts[2]}${dateParts[1]}';

    final basePrefix = '$typePrefix-$namePrefix-$datePrefix';

    // Find max sequence
    final matchingItems = existingItems
        .where((item) =>
            item.sourceResource != null &&
            item.sourceResource!.startsWith(basePrefix))
        .toList();

    int nextSeq = 1;
    if (matchingItems.isNotEmpty) {
      final sequences = matchingItems
          .map((item) {
            final parts = item.sourceResource!.split('-');
            if (parts.length >= 4) {
              return int.tryParse(parts[3]) ?? 0;
            }
            return 0;
          })
          .where((seq) => seq > 0)
          .toList();

      if (sequences.isNotEmpty) {
        nextSeq = sequences.reduce(max) + 1;
      }
    }

    final seqPart = nextSeq.toString().padLeft(3, '0');
    final sameSuffix = _currentQueueIndex != -1 ? '-SAME' : '';

    return '$basePrefix-$seqPart$sameSuffix';
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    // Build methods will be added in next part
    return Scaffold(
      body: SafeArea(
        child: Consumer<InventoryProvider>(
          builder: (context, inventoryProvider, child) {
            return RefreshIndicator(
              onRefresh: _handleRefresh,
              color: AppConstants.limeGreen,
              child: SingleChildScrollView(
                physics: const AlwaysScrollableScrollPhysics(),
                padding: const EdgeInsets.fromLTRB(24, 24, 24, 110),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    AppBarGlass(
                      mode: AppBarMode.title,
                      title: _selectedCategory ?? 'Farm Inventory',
                      subtitle: _selectedCategory != null
                          ? 'Manage your ${_selectedCategory!.toLowerCase()} stocks'
                          : 'Resource and stock management',
                      leadingAction: _selectedCategory != null
                          ? IconButton(
                              onPressed: () {
                                setState(() {
                                  _selectedCategory = null;
                                  _searchQuery = '';
                                });
                              },
                              icon: const Icon(Icons.arrow_back),
                            )
                          : null,
                    ),
                    const SizedBox(height: 24),
                    if (_selectedCategory == null) ...[
                      _buildCategoryGrid(inventoryProvider),
                    ] else ...[
                      _buildItemsList(inventoryProvider),
                    ],
                    if (_showForm) ...[
                      const SizedBox(height: 24),
                      _buildForm(),
                    ],
                  ],
                ),
              ),
            );
          },
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _handleAddNew,
        backgroundColor: AppConstants.limeGreen,
        icon: const Icon(Icons.add, color: Colors.white),
        label: Text(
          'Add Item',
          style: DesignSystem.text(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Colors.white,
          ),
        ),
      ),
    );
  }

  Widget _buildSummaryCards(InventoryProvider provider) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isMobile = constraints.maxWidth < 600;

        return isMobile
            ? Column(
                children: [
                  _buildSummaryCard(
                    'Available Stock',
                    provider.items
                        .fold(0.0, (sum, item) => sum + item.quantityAvailable)
                        .toStringAsFixed(0),
                    Icons.inventory_2,
                    AppConstants.limeGreen,
                  ),
                  const SizedBox(height: 12),
                  _buildSummaryCard(
                    'Total Assets',
                    provider.items.length.toString(),
                    Icons.layers,
                    AppConstants.forestGreen,
                  ),
                  const SizedBox(height: 12),
                  _buildSummaryCard(
                    'Current Value',
                    'LKR ${provider.items.fold(0.0, (sum, item) => sum + item.totalValue).toStringAsFixed(0)}',
                    Icons.attach_money,
                    Colors.amber,
                  ),
                ],
              )
            : Row(
                children: [
                  Expanded(
                    child: _buildSummaryCard(
                      'Available Stock',
                      provider.items
                          .fold(0.0, (sum, item) => sum + item.quantityAvailable)
                          .toStringAsFixed(0),
                      Icons.inventory_2,
                      AppConstants.limeGreen,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: _buildSummaryCard(
                      'Total Assets',
                      provider.items.length.toString(),
                      Icons.layers,
                      AppConstants.forestGreen,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: _buildSummaryCard(
                      'Current Value',
                      'LKR ${provider.items.fold(0.0, (sum, item) => sum + item.totalValue).toStringAsFixed(0)}',
                      Icons.attach_money,
                      Colors.amber,
                    ),
                  ),
                ],
              );
      },
    );
  }

  Widget _buildSummaryCard(
      String label, String value, IconData icon, Color color) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return GlassCard(
      intensity: GlassIntensity.medium,
      child: Container(
        padding: const EdgeInsets.all(20),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(14),
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Icon(icon, color: color, size: 28),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    label.toUpperCase(),
                    style: DesignSystem.text(
                      fontSize: 10,
                      fontWeight: FontWeight.w800,
                      letterSpacing: 1.0,
                      color: isDark
                          ? Colors.white.withValues(alpha: 0.6)
                          : Colors.grey[600],
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    value,
                    style: DesignSystem.heading(
                      fontSize: 22,
                      fontWeight: FontWeight.w900,
                      color: isDark ? Colors.white : Colors.black87,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCategoryGrid(InventoryProvider provider) {
    final categoryStats = provider.getCategoryStats();

    return LayoutBuilder(
      builder: (context, constraints) {
        final crossAxisCount = constraints.maxWidth > 1200
            ? 4
            : constraints.maxWidth > 900
                ? 3
                : constraints.maxWidth > 600
                    ? 2
                    : 1;

        return GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: crossAxisCount,
            childAspectRatio: 1.2,
            crossAxisSpacing: 16,
            mainAxisSpacing: 16,
          ),
          itemCount: _categoryConfig.length,
          itemBuilder: (context, index) {
            final category = _categoryConfig.keys.elementAt(index);
            final config = _categoryConfig[category]!;
            final stats = categoryStats[category]!;

            return InventoryStatCard(
              icon: config.icon,
              iconColor: config.color,
              bgColor: config.bgColor,
              category: category,
              itemCount: stats.itemCount,
              totalQuantity: stats.totalQuantity,
              onTap: () {
                setState(() {
                  _selectedCategory = category;
                });
              },
            );
          },
        );
      },
    );
  }

  Widget _buildItemsList(InventoryProvider provider) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    final filteredItems = provider.items.where((item) {
      final matchesCategory = item.category == _selectedCategory;
      final matchesSearch = _searchQuery.isEmpty ||
          item.itemName.toLowerCase().contains(_searchQuery.toLowerCase()) ||
          (item.sourceResource?.toLowerCase().contains(_searchQuery.toLowerCase()) ?? false);
      return matchesCategory && matchesSearch;
    }).toList();

    if (filteredItems.isEmpty) {
      return _buildEmptyState(isDark);
    }

    return Column(
      children: [
        // Search bar
        Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: TextField(
            decoration: InputDecoration(
              hintText: 'Search items...',
              prefixIcon: Icon(Icons.search, color: AppConstants.limeGreen),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            onChanged: (value) {
              setState(() {
                _searchQuery = value;
              });
            },
          ),
        ),

        // Items list
        ListView.separated(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          itemCount: filteredItems.length,
          separatorBuilder: (context, index) => const SizedBox(height: 16),
          itemBuilder: (context, index) {
            final item = filteredItems[index];
            return _buildItemCard(item, isDark);
          },
        ),
      ],
    );
  }

  Widget _buildItemCard(InventoryItem item, bool isDark) {
    return GlassCard(
      intensity: GlassIntensity.medium,
      child: Container(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header row
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: _categoryConfig[item.category]!.bgColor,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Icon(
                    _categoryConfig[item.category]!.icon,
                    color: _categoryConfig[item.category]!.color,
                    size: 24,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        item.itemName,
                        style: DesignSystem.heading(
                          fontSize: 18,
                          fontWeight: FontWeight.w900,
                          color: isDark ? Colors.white : Colors.black87,
                        ),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                      ),
                      Text(
                        item.inventoryType,
                        style: DesignSystem.text(
                          fontSize: 11,
                          fontWeight: FontWeight.bold,
                          color: AppConstants.limeGreen,
                        ),
                      ),
                    ],
                  ),
                ),
                PopupMenuButton(
                  icon: Icon(
                    Icons.more_vert,
                    color: isDark ? Colors.white60 : Colors.grey[600],
                  ),
                  itemBuilder: (context) => [
                    PopupMenuItem(
                      child: Row(
                        children: [
                          Icon(Icons.tune, size: 18, color: AppConstants.limeGreen),
                          const SizedBox(width: 8),
                          const Text('Adjust Stock'),
                        ],
                      ),
                      onTap: () {
                        Future.delayed(Duration.zero, () {
                          showDialog(
                            context: context,
                            builder: (context) => StockAdjustmentModal(
                              item: item,
                              onSuccess: _handleRefresh,
                            ),
                          );
                        });
                      },
                    ),
                    PopupMenuItem(
                      child: Row(
                        children: [
                          const Icon(Icons.history, size: 18, color: Colors.blue),
                          const SizedBox(width: 8),
                          const Text('View History'),
                        ],
                      ),
                      onTap: () {
                        Future.delayed(Duration.zero, () {
                          showDialog(
                            context: context,
                            builder: (context) => InventoryHistoryModal(
                              itemId: item.id,
                              itemName: item.itemName,
                              onClose: () {},
                            ),
                          );
                        });
                      },
                    ),
                    PopupMenuItem(
                      child: Row(
                        children: [
                          const Icon(Icons.edit, size: 18, color: Colors.orange),
                          const SizedBox(width: 8),
                          const Text('Edit'),
                        ],
                      ),
                      onTap: () => _handleEdit(item),
                    ),
                    PopupMenuItem(
                      child: Row(
                        children: [
                          const Icon(Icons.delete, size: 18, color: Colors.red),
                          const SizedBox(width: 8),
                          const Text('Delete'),
                        ],
                      ),
                      onTap: () => _handleDelete(item.id, item.itemName),
                    ),
                  ],
                ),
              ],
            ),
            const SizedBox(height: 16),

            // Stats row
            Row(
              children: [
                Expanded(
                  child: _buildItemStat(
                    'Available',
                    '${item.quantityAvailable} ${item.unit}',
                    '${item.percentAvailable.toStringAsFixed(0)}%',
                    isDark,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _buildItemStat(
                    'Value',
                    'LKR ${item.totalValue.toStringAsFixed(0)}',
                    'LKR ${item.unitPrice.toStringAsFixed(2)}/${item.unit}',
                    isDark,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _buildItemStat(
                    'Batch',
                    item.sourceResource ?? 'N/A',
                    item.purchaseDate,
                    isDark,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildItemStat(String label, String value, String subtitle, bool isDark) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: DesignSystem.text(
            fontSize: 9,
            fontWeight: FontWeight.w800,
            letterSpacing: 0.5,
            color: isDark ? Colors.white.withValues(alpha: 0.6) : Colors.grey[600],
          ),
        ),
        const SizedBox(height: 4),
        Text(
          value,
          style: DesignSystem.text(
            fontSize: 13,
            fontWeight: FontWeight.bold,
            color: isDark ? Colors.white : Colors.black87,
          ),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
        Text(
          subtitle,
          style: DesignSystem.text(
            fontSize: 10,
            color: isDark ? Colors.white.withValues(alpha: 0.5) : Colors.grey[500],
          ),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
      ],
    );
  }

  Widget _buildEmptyState(bool isDark) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(48),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.inventory_2_outlined,
              size: 80,
              color: isDark ? Colors.white24 : Colors.grey[300],
            ),
            const SizedBox(height: 16),
            Text(
              'No items yet',
              style: DesignSystem.heading(
                fontSize: 20,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white54 : Colors.grey[600],
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Add your first item to get started',
              style: DesignSystem.text(
                fontSize: 14,
                color: isDark ? Colors.white38 : Colors.grey[500],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildForm() {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    // Auto-generate batch number
    if (_isBatchAutoGenerated && _editingId == null) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        final newBatch = _generateBatchNumber();
        if (newBatch != _formData['source_resource']) {
          setState(() {
            _formData['source_resource'] = newBatch;
          });
        }
      });
    }

    return GlassCard(
      intensity: GlassIntensity.large,
      child: Container(
        padding: const EdgeInsets.all(28),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                children: [
                  Icon(
                    _editingId != null ? Icons.edit : Icons.add_circle_outline,
                    color: AppConstants.limeGreen,
                    size: 28,
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      _editingId != null ? 'Edit Item' : 'Add New Item',
                      style: DesignSystem.heading(
                        fontSize: 22,
                        fontWeight: FontWeight.w900,
                        color: isDark ? Colors.white : Colors.black87,
                      ),
                    ),
                  ),
                  IconButton(
                    onPressed: _closeForm,
                    icon: Icon(
                      Icons.close,
                      color: isDark ? Colors.white60 : Colors.grey[600],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              // Form fields
              LayoutBuilder(
                builder: (context, constraints) {
                  final isMobile = constraints.maxWidth < 600;

                  return isMobile
                      ? Column(
                          children: _buildFormFields(isDark),
                        )
                      : Wrap(
                          spacing: 16,
                          runSpacing: 16,
                          children: _buildFormFields(isDark),
                        );
                },
              ),

              const SizedBox(height: 24),

              // Action buttons
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton(
                      onPressed: _closeForm,
                      style: OutlinedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 14),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                      ),
                      child: Text(
                        'Cancel',
                        style: DesignSystem.text(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    flex: 2,
                    child: ElevatedButton(
                      onPressed: _handleSubmit,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppConstants.limeGreen,
                        padding: const EdgeInsets.symmetric(vertical: 14),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                      ),
                      child: Text(
                        _editingId != null ? 'Update Item' : 'Create Item',
                        style: DesignSystem.text(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  List<Widget> _buildFormFields(bool isDark) {
    return [
      SizedBox(
        width: 280,
        child: _buildTextField(
          'Item Name',
          'item_name',
          'e.g., NPK Fertilizer',
          isDark,
        ),
      ),
      SizedBox(
        width: 280,
        child: _buildDropdown(
          'Category',
          'category',
          _categoryConfig.keys.toList(),
          isDark,
          isLocked: _selectedCategory != null && _editingId == null ||
              _currentQueueIndex != -1,
        ),
      ),
      SizedBox(
        width: 280,
        child: _buildDropdown(
          'Type',
          'inventory_type',
          _inventoryTypes,
          isDark,
        ),
      ),
      SizedBox(
        width: 280,
        child: _buildTextField(
          'Quantity',
          'quantity_purchased',
          '0',
          isDark,
          keyboardType: TextInputType.number,
        ),
      ),
      SizedBox(
        width: 280,
        child: _buildDropdown(
          'Unit',
          'unit',
          _units,
          isDark,
        ),
      ),
      SizedBox(
        width: 280,
        child: _buildTextField(
          'Unit Price (LKR)',
          'unit_price',
          '0.00',
          isDark,
          keyboardType: TextInputType.number,
        ),
      ),
      SizedBox(
        width: 280,
        child: _buildDateField('Purchase Date', 'purchase_date', isDark),
      ),
      SizedBox(
        width: 580,
        child: _buildTextField(
          'Batch Number',
          'source_resource',
          'Auto-generated',
          isDark,
          isReadOnly: _editingId != null || _currentQueueIndex != -1,
        ),
      ),
    ];
  }

  Widget _buildTextField(
    String label,
    String key,
    String hint,
    bool isDark, {
    TextInputType? keyboardType,
    bool isReadOnly = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: DesignSystem.text(
            fontSize: 10,
            fontWeight: FontWeight.w800,
            letterSpacing: 1.0,
            color: isDark ? Colors.white.withValues(alpha: 0.6) : Colors.grey[600],
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          initialValue: _formData[key].toString(),
          readOnly: isReadOnly,
          keyboardType: keyboardType,
          decoration: InputDecoration(
            hintText: hint,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
          onChanged: (value) {
            setState(() {
              _formData[key] = value;
              if (key == 'source_resource') {
                _isBatchAutoGenerated = false;
              }
            });
          },
          validator: (value) {
            if (key == 'source_resource') return null; // Optional
            if (value == null || value.isEmpty) {
              return '$label is required';
            }
            if ((key == 'quantity_purchased' || key == 'unit_price') &&
                double.tryParse(value) == null) {
              return 'Invalid number';
            }
            return null;
          },
        ),
      ],
    );
  }

  Widget _buildDropdown(
    String label,
    String key,
    List<String> options,
    bool isDark, {
    bool isLocked = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: DesignSystem.text(
            fontSize: 10,
            fontWeight: FontWeight.w800,
            letterSpacing: 1.0,
            color: isDark ? Colors.white.withValues(alpha: 0.6) : Colors.grey[600],
          ),
        ),
        const SizedBox(height: 8),
        DropdownButtonFormField<String>(
          initialValue: _formData[key].toString(),
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
          items: options
              .map((option) => DropdownMenuItem(
                    value: option,
                    child: Text(option),
                  ))
              .toList(),
          onChanged: isLocked
              ? null
              : (value) {
                  if (value != null) {
                    setState(() {
                      _formData[key] = value;
                    });
                  }
                },
        ),
        if (isLocked)
          Padding(
            padding: const EdgeInsets.only(top: 4, left: 4),
            child: Text(
              _currentQueueIndex != -1
                  ? 'Sequential category locked'
                  : 'Locked to current view',
              style: DesignSystem.text(
                fontSize: 10,
                fontWeight: FontWeight.bold,
                color: AppConstants.limeGreen,
              ).copyWith(fontStyle: FontStyle.italic),
            ),
          ),
      ],
    );
  }

  Widget _buildDateField(String label, String key, bool isDark) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: DesignSystem.text(
            fontSize: 10,
            fontWeight: FontWeight.w800,
            letterSpacing: 1.0,
            color: isDark ? Colors.white.withValues(alpha: 0.6) : Colors.grey[600],
          ),
        ),
        const SizedBox(height: 8),
        InkWell(
          onTap: () async {
            final date = await showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime(2020),
              lastDate: DateTime.now(),
            );
            if (date != null) {
              setState(() {
                _formData[key] =
                    '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
              });
            }
          },
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
            decoration: BoxDecoration(
              border: Border.all(
                color: isDark
                    ? Colors.white.withValues(alpha: 0.3)
                    : Colors.grey[400]!,
              ),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                Icon(Icons.calendar_today, size: 18, color: AppConstants.limeGreen),
                const SizedBox(width: 12),
                Text(
                  _formData[key].toString(),
                  style: DesignSystem.text(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                    color: isDark ? Colors.white : Colors.black87,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

class CategoryConfig {
  final IconData icon;
  final Color color;
  final Color bgColor;

  CategoryConfig({
    required this.icon,
    required this.color,
    required this.bgColor,
  });
}
